server:
  port: 8761
  http2:
    enabled: true
  ssl:
    enabled : true
    key-alias: Eureka_ssl
    key-store: classpath:Eureka-ssl.p12
    key-store-type: PKCS12
    key-password: root123
    key-store-password: root123  
  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #    our server shouldnot register itself as client...
    fetch-registry: false     #    It shouldnot fetch server as client...
 