server:
  port: 9000
  http2:
    enabled: true
  ssl:
    enabled : true
    key-alias: local_ssl
    key-store: classpath:local-ssl.p12
    key-store-type: PKCS12
    key-password: root123
    key-store-password: root123  

    trust-store: classpath:local-ssl.p12
    trust-store-password: root123
    trust-store-type: PKCS12
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_mc
#    url: jdbc:mysql://${MYSQL_HOST}:3306/test
    username: root
    password: I43_mummy
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: USER-SERVICE   
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql : true 
        
#MYSQL_HOST: 10.0.60.218
        
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    secure-port-enabled: true
  client:
    fetch-registry: true         # It has to register itself as client
    register-with-eureka: true    #It has to fetch as client
    service-url:
      defaultZone : https://localhost:8761/eureka    #This service will use this url inorder to register with server... 
    
    
    tls:
      enabled : true
#      key-alias: local_ssl
      key-store: classpath:local-ssl.p12
      key-store-type: PKCS12
      key-password: root123
      key-store-password: root123  
      trust-store: classpath:local-ssl.p12
      trust-store-type: PKCS12
      trust-store-password: root123
      
feign:
  httpclient:
    disable-ssl-validation: true
    enabled: false
  okhttp:
    enabled: false
      

    
    
      
      
      